### ISSUE TITLE
Construir el Tablero de visión del producto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo2_sn_ppi2020#5]

**Comment by JohnFlorez25** [comment]
@valentina2121 @Andreiitha @AlexandraG-T mejorar la descripciòn de la visión del producto de acuerdo a la estructura que esta contemplada en la guía de la semana 2 del módulo de IR - Análisis del Problema, los interesados deben ser los que estén descritos en cada cuadro y las demás categorías deben tener como mínimo 3 descripciones.

**Comment by Andreiitha** [comment]
Profe los cambios de hoy los hicimos AlexandraG-T  y yo veronica muñoz, y lo enviamos solo por el perfil mio Andreiitha ya que estabamos reunidas
